export const techStacks = {
  cloud: [
    "Google Cloud Platform",
    "Cloud Run",
    "Cloud Build",
    "IAM & Least Privilege",
    "GCP KMS",
    "Docker",
    "GitHub Actions",
    "GitOps",
    "VPC Networking",
  ],
  security: [
    "IAM Least Privilege & Service Scoping",
    "AES-256-GCM Envelope Encryption",
    "Google OIDC & RSA JWT Signing",
    "Structured Security Audit Logging",
    "Cloud Security Assessment",
    "RA 10173 DPA Compliance",
  ],
  languages: [
    "Go (Golang)",
    "Python",
    "C# (.NET Core)",
    "SQL",
    "TypeScript",
    "Dart (Flutter)",
    "Bash",
  ],
  backend: [
    "Custom Go API Gateway",
    "FastAPI (Python)",
    ".NET Core",
    "Reverse Proxying",
    "gRPC / HTTP/2",
    "WebSockets / SSE",
  ],
  databases: ["PostgreSQL", "Redis", "MongoDB", "AWS S3"],
  frontend: ["React", "Flutter", "Tailwind CSS"],
} as const;
